//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRMWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageId { get; set; }
        public int TenantId { get; set; }
        public int ManagerId { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
    
        public virtual PotentialTenant PotentialTenant { get; set; }
        public virtual PropertyManager PropertyManager { get; set; }
    }
}
